/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package allguis;
import guiConsoleController.ChooseThemeController;
import guiConsoleController.I_ChooseTheme;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import tegakari.*;

/**
 *
 * @author Tarrant
 */
public class ChooseThemeDialog extends javax.swing.JDialog implements I_ChooseTheme
{
    private ThemeType themeType;
    private LobbyGUI gui;
    private ChooseThemeController ctrl;
    
    private String greekOne = "/image/GreeceImages/Suspects-Aphrodite.jpg";
    private String greekTwo = "/image/GreeceImages/Transportation-HadesDogs.jpg";
    private String pirateOne = "/image/PirateImages/blackbeardcard.jpg";
    private String pirateTwo = "/image/PirateImages/barquecard.jpg";
    private String washingtonOne = "/image/WhiteHouseImages/Destination-Yellowstone.jpg";
    private String washingtonTwo = "/image/WhiteHouseImages/Suspect-Karl.jpg";
    
    /**
     * Creates new form ChooseThemeDialog
     * 
     * @param parent the parent frame
     * @param ctrl controller, eventHandler for ChooseThemeDialog
     * @param modal modal setting for JDialog
     */
    public ChooseThemeDialog(java.awt.Frame parent, boolean modal, 
            ChooseThemeController ctrl) 
    {
        super(parent, modal);
        initComponents();
        this.themeType = ThemeType.GREEK;
        gui = (LobbyGUI) parent;
        
        setNames();
        
        confirmSelectionButton.addActionListener(ctrl);
        confirmSelectionButton.setActionCommand("OK");
        confirmSelectionButton.addKeyListener(ctrl);
        
        
        
        greekRadio.addActionListener(ctrl);
        greekRadio.setActionCommand("G");
        greekRadio.addKeyListener(ctrl);
        
        pirateRadio.addActionListener(ctrl);
        pirateRadio.setActionCommand("P");
        pirateRadio.addKeyListener(ctrl);
        
        washingtonRadio.addActionListener(ctrl);
        washingtonRadio.setActionCommand("W");
        washingtonRadio.addKeyListener(ctrl);
        
        ButtonGroup group = new ButtonGroup();
        group.add(greekRadio);
        group.add(pirateRadio);
        group.add(washingtonRadio);
    }
    
    /**
     * Returns the Theme Chosen so the LobbyGUI can see which one is the current
     * theme
     * @return the current theme
    */
    public ThemeType getTheme()
    {
        return this.themeType;
    }
    
    public void setGreekImages()
    {
        leftImage.setIcon(new ImageIcon(getClass().getResource(greekOne)));
        rightImage.setIcon(new ImageIcon(getClass().getResource(greekTwo)));
        
        greekRadio.setSelected(true);
    }
    
    public void setPirateImages()
    {
        leftImage.setIcon(new ImageIcon(getClass().getResource(pirateOne)));
        rightImage.setIcon(new ImageIcon(getClass().getResource(pirateTwo)));
        
        pirateRadio.setSelected(true);
    }
    
    public void setWashingtonImages() 
    {
        leftImage.setIcon(new ImageIcon(getClass().getResource(washingtonOne)));
        rightImage.setIcon(new ImageIcon(getClass().getResource(washingtonTwo)));
        
        washingtonRadio.setSelected(true);
    }
    
    public void setBlankImages()
    {
        leftImage.setIcon(new ImageIcon());
        rightImage.setIcon(new ImageIcon());
    }
    private void setNames()
    {
        greekRadio.setName("chooseGreek");
        pirateRadio.setName("choosePirate");
        washingtonRadio.setName("chooseWashington");
        confirmSelectionButton.setName("confirmSelectionButton");
        titleText.setName("titleText");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleText = new javax.swing.JLabel();
        confirmSelectionButton = new javax.swing.JButton();
        displayImageRight = new javax.swing.JLabel();
        displayImageLeft = new javax.swing.JLabel();
        leftImage = new javax.swing.JLabel();
        rightImage = new javax.swing.JLabel();
        greekRadio = new javax.swing.JRadioButton();
        pirateRadio = new javax.swing.JRadioButton();
        washingtonRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("ChooseThemeDialog"); // NOI18N

        titleText.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 36)); // NOI18N
        titleText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        titleText.setText("<HTML>Choose<br>Theme<HTNML>");

        confirmSelectionButton.setText("OK (SPACE)");
        confirmSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmSelectionButtonActionPerformed(evt);
            }
        });

        greekRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        greekRadio.setText("(G)REEK");

        pirateRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pirateRadio.setText("(P)IRATE");

        washingtonRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        washingtonRadio.setText("(W)ASHINGTON");
        washingtonRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                washingtonRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(displayImageLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(leftImage, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rightImage, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayImageRight)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(greekRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pirateRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(washingtonRadio)
                                .addGap(31, 31, 31))
                            .addComponent(confirmSelectionButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayImageLeft)
                            .addComponent(displayImageRight))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(leftImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(washingtonRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pirateRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greekRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(confirmSelectionButton)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void confirmSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmSelectionButtonActionPerformed
        
    }//GEN-LAST:event_confirmSelectionButtonActionPerformed

    private void washingtonRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_washingtonRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_washingtonRadioActionPerformed

    public void okEnable(boolean visible)
    {
        confirmSelectionButton.setEnabled(visible);
    }
      
    public LobbyGUI getGUI()
    {
        return this.gui;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmSelectionButton;
    private javax.swing.JLabel displayImageLeft;
    private javax.swing.JLabel displayImageRight;
    private javax.swing.JRadioButton greekRadio;
    private javax.swing.JLabel leftImage;
    private javax.swing.JRadioButton pirateRadio;
    private javax.swing.JLabel rightImage;
    private javax.swing.JLabel titleText;
    private javax.swing.JRadioButton washingtonRadio;
    // End of variables declaration//GEN-END:variables

}
